# --- Stages -------------------------------------------------------------------

stages:
  - prep
  - test
  - build
  - deploy

# --- Common -------------------------------------------------------------------

image: node:lts

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

# --- Prep stage ---------------------------------------------------------------

# --- Test stage ---------------------------------------------------------------

test:
  stage: test
  script:
    - npm run lint
    - npm run test:unit

# --- Build stage --------------------------------------------------------------

build:
  stage: build
  only:
    - beta
  variables:
    # Axios base URL
    VUE_APP_API_BASE_URL: "https://documatt-snippets-api-dev.herokuapp.com/api/v1/"
  script:
    - export VUE_APP_GIT_REV=`git rev-parse --short HEAD`
    - npm run build
  artifacts:
    paths:
      - dist

# --- Deploy stage -------------------------------------------------------------

# Frontend deploy to GitLab Pages (job must be named "pages")
#pages:
#    stage: deploy
#    only:
#        - beta
#    script:
#        - mkdir public
#        - mv web/dist/* public
#    artifacts:
#        paths:
#            - public

s3:
  stage: deploy
  only:
    - beta
  image:
    name: amazon/aws-cli:2.1.3
    # to use amazon/aws-cli as job image, we need to clear entrypoint image
    # ("aws")
    entrypoint: [""]
  # reset global "before_script" that restore NPM cache (npm command is not
  # in this image)
  before_script:
    # ":" is noop bash command
    - ":"
  # reset global "cache" suitable for NPM only
  cache: {}
  variables:
    # We always use us-east-2
    AWS_DEFAULT_REGION: us-east-2
    # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are set from GitLab CI GUI
  script:
    - echo $AWS_ACCESS_KEY_ID
    - aws --version
    - aws s3 sync dist s3://documatt-snippets-web
